apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: mvn
spec:
  workspaces:
  - name: maven-repo
  inputs:
    params:
    - name: GOALS
      description: The Maven goals to run
      type: array
      default: ["package"]
  steps:
steps:
  - name: check-java-version
    image: gcr.io/cloud-builders/mvn
    script: |
      #!/bin/sh
      java -version
      mvn -v
