apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-spring-boot
spec:
  description: |
     This pipeline clone a spring-boot git repo
  params: 
  - name: repo-url
    type: string 
    description: The git repo URL to clone from
  - name: user
    type: string 
    description: user for image-registry
  - name: pass
    type: string 
    description: pass for docker-reg
  - name: image-name 
    type: string 
    description: image-name for build

  workspaces:
    - name: shared-data 
      description: |
        this workspace contains the cloned repo files       
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone 
      workspaces:
        - name: output
          workspace: shared-data 
      params:
        - name: url 
          value: $(params.repo-url)
  
    - name: build-and-deploy
      runAfter:
        - fetch-source 
      taskRef:
        name: s2i-java
      params:
        - name: user 
          value: $(params.user)
        - name: pass 
          value: $(params.pass) 
        - name: image-name 
          value: $(params.image-name)
      workspaces:
        - name: mehmet 
          workspace: shared-data
