---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: s2i-spring-boot
spec:
  workspaces:
    - name: mehmet
  params:
    - name: user
      type: string
    - name: pass
      type: string
    - name: image-name
      type: string
    - name: registry
      type: string
      default: "docker.io"
  steps:
    - name: analyse-1
      image: quay.io/buildah/stable
      workingDir: $(workspaces.mehmet.path)
      script: |
         #!/usr/bin/env sh
         pwd 
         ls -al
         ls -al $(workspaces.mehmet.path) 

    - name: build
      image: quay.io/buildah/stable
      workingDir: "$(workspaces.mehmet.path)"
      command: ["buildah", "bud", "--tls-verify=false", "--layers", "-t", "$(params.registry)/$(params.user)/$(params.image-name)", "Dockerfile"]
      securityContext:
        privileged: true
      volumeMounts:
      - name: varlibcontainers
        mountPath: /var/lib/containers
     


    - name: push
      image: quay.io/buildah/stable
      workingDir: "$(workspaces.mehmet.path)"
      command: ['buildah', 'push', '--creds=$(params.user):$(params.pass)', '--tls-verify=false', '$(params.registry)/$(params.user)/$(params.image-name)', 'docker://$(params.registry)/$(params.user)/$(params.image-name)']
      securityContext:
        privileged: true
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
  volumes:
    - name: varlibcontainers
      emptyDir: {}
