apiVersion: v1
kind: Pod
metadata:
  name: pvc-debugger2
spec:
  containers:
  - name: debug-container
    image: busybox
    command:
      - sh
      - -c
      - "sleep 3600" # Pod'un çalışır durumda kalması için
    volumeMounts:
    - mountPath: "/data"
      name: pvc-volume
  volumes:
  - name: pvc-volume
    persistentVolumeClaim:
      claimName: pvc-c95934d586
