apiVersion: apps/v1
kind: Deployment
metadata:
  name: mehmetspringboot-deployment
  namespace: mehmet  
  labels:
    app: mehmetspringboot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mehmetspringboot
  template:
    metadata:
      labels:
        app: mehmetspringboot
    spec:
      containers:
        - name: mehmetspringboot
          image: mekar43/mehmetspringboot:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: mehmetspringboot-service
  namespace: mehmet 
  labels:
    app: mehmetspringboot
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: mehmetspringboot
