apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mehmetspringboot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/azmerkar/springboottektonargocddemo1.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
